type User @table {
  username: String!
  createdAt: Timestamp!
  email: String
  bio: String
  photoUrl: String
}

type Channel @table {
  name: String!
  isPrivate: Boolean!
  createdAt: Timestamp!
  description: String
  host: User!
}

type ChannelParticipant @table(key: ["user", "channel"]) {
  user: User!
  channel: Channel!
  joinedAt: Timestamp!
  isSpeaker: Boolean!
}

type Follow @table(key: ["follower", "followed"]) {
  follower: User!
  followed: User!
  createdAt: Timestamp!
}

type Report @table {
  reason: String!
  createdAt: Timestamp!
  details: String
  reporter: User!
  reportedChannel: Channel
  reportedParticipant: User
}